### ISSUE TITLE
anndata compression in benchmark

### ISSUE THREAD

**Issue by ivirshup** [bnprks/BPCells#10]
Hey all, just wanted to raise a quick issue about the benchmarks:

> BPCells uses bitpacking compression to provide 4-6x smaller storage for counts matrices compared to an uncompressed binary format like AnnData.

AnnData isn't inherently uncompressed. You can specify the kind of compression used in the hdf5 format with the `compression` key word argument ([docs](https://anndata.readthedocs.io/en/latest/generated/anndata.AnnData.write.html#anndata.AnnData.write)). You could use more modern (and much faster) compressors like `lzf` and `zstd` as well, but there may be compatibility with different hdf5 libraries.

With the zarr format, you have access to a much wider range of compressors, with `blosc` used by default.

**Comment by bnprks** [comment]
Hi Isaac, thanks for reaching out, and great job with the AnnData library!

Your point is well taken about the large number of compression options available with AnnData. As a quick adjustment, I'll try clarifying the text + figure label to specify this is comparing to uncompressed h5ad files. In a quick summary like on the website, I have limited space for full comparisons. I chose uncompressed h5ad mainly because it's the default option from the `AnnData.write` function and what I see most commonly in the wild.

I have not had a chance to compare against lzf or blosc yet, so I'll give that a try and provide an update here. 

I have some more preliminary benchmarks not on the website comparing to zstd and lz4, which shows the bitpacking compression on scRNA counts matrices still provides convincing advantages for read + write speeds, and is only beaten on compression ratio by zstd at the cost of much slower write speeds. (A few representative timings listed below)

Of course the bitpacking compression BPCells uses is not a general-purpose algorithm, but rather specialized to work quickly on sparse, non-negative integer matrices. I think that is a large part of why it is possible to outperform much more sophisticated general-purpose compression algorithms. 

My high-level point would be that bitpacking compression is fast enough to read+write that it could reasonably replace uncompressed data as a default storage format for sharing and working on datasets (at least when floating point values are not needed).

In this benchmark setup, I was compressing binary files containing the row + val arrays as uint32s for the 1.3M cell 10x dataset. I used a ramdisk (/dev/shm) to take disk speed out of the equation. Actual times can vary with RAM + CPU clock speeds, but the relative times seem fairly consistent. The uncompressed input data size is 21GB.

| Method  | Data size | Write time | Read time |
| ------- | --------- | ---------- | --------- |
| BPCells | 4.8GB     | 10.0s      | 10.5s     |
| zstd -1 | 5.5GB     | 72.4s      | 31.5s     |
| zstd -2 | 4.9GB     | 82.4s      | 33.7s     |
| zstd -9 | 3.7GB     | 506s       | 25.5s     |
| lz4 -1  | 11.0GB    | 41.5s      | 16.0s     |
| lz4 -9  | 5.6GB     | 1,900s     | 15.1s     |
| gzip -1 | 6.0GB     | 336s       | 135s      |
| gzip -9 | 4.8GB     | 9,253s     | 102s      |

**Comment by bnprks** [comment]
Oh, quick followup question -- do you have recommendations for the best non-default zarr compression option? (in this case optimizing for fastest read+write while roughly matching gzip compression ranges on single cell RNA counts matrices)

**Comment by bnprks** [comment]
Just a quick update -- I clarified the text on the [performance benchmarks](https://bnprks.github.io/BPCells/articles/web-only/benchmarks.html#bitpacking-compression) section of the website, with some clarified text, figure legends, and a footnote that I hope will keep readers from being confused. Hope that addresses your initial concerns

**Comment by bnprks** [comment]
> Do you think you could point me at the dataset you're using to benchmark here? I'd be interested in playing around with it a bit.

Sure, dataset is just the publicly distributed 1.3M cell dataset by 10x: [email-walled link](https://www.10xgenomics.com/resources/datasets/1-3-million-brain-cells-from-e-18-mice-2-standard-1-3-0), [direct hdf5 download](https://cf.10xgenomics.com/samples/cell-exp/1.3.0/1M_neurons/1M_neurons_filtered_gene_bc_matrices_h5.h5) (4.2GB). I used SSD storage for the benchmarks above.

> To me the main concern with defaults is compatibility. Being able to be cross language is really one of the most important things about anndata, so I'd need to look into if this compression could be done in a way accessible across languages. For zarr, this is probably pretty possible, but filter plugins to hdf5 can be fraught.

From a cross-language compatibility perspective, BPCells doesn't actually use an hdf5 filter when storing in an hdf5 file. Rather, a matrix is stored as ~8 uncompressed int arrays that themselves contain compressed data. The core bitpacking logic is pretty small -- about 15 lines each for compress/decompress. (to make fully functioning, seekable read/write maybe 1k lines total including comments). So language compatibility would be achieved through ease of re-implementation or re-use of a small amount of C++  code, which is my plan for python support.

In practice, I'm not sure how cross-compatible zarr is right now for an R user -- there doesn't appear to be a native R implementation listed in these [zarr docs](https://github.com/zarr-developers/zarr_implementations). Given the promising progress in C++/Rust/Java implementations, hopefully it will come to R sooner or later.

> But, playing around with it a bit, the default compressor in zarr (shuffle + LZ4) seems quite good.

For the python side of the single cell ecosystem, I agree that zarr with its default blosc settings seems pretty decent. I might argue bitpacking has some speed advantages given my earlier benchmarks, but zarr's default blosc+lz4 seems to provide acceptable performance.

One technical difference I've noticed is that blosc here defaults to >=65KB block sizes, whereas bitpacking can decompress at 512B granularity. This may be useful for random seeks (reading individual matrix rows/columns), but I don't know how to benchmark partial reads on anndata. Does one of the experimental AnnData APIs support reading the data for just a single random cell?

**Comment by ivirshup** [comment]
> In practice, I'm not sure how cross-compatible zarr is right now for an R user -- there doesn't appear to be a native R implementation listed in these [zarr docs](https://github.com/zarr-developers/zarr_implementations). Given the promising progress in C++/Rust/Java implementations, hopefully it will come to R sooner or later.

I think sooner! @grimbough (of bioconductor) is currently working on this with `rarr` ([github repo](https://github.com/grimbough/Rarr), [bioc submission](https://github.com/Bioconductor/Contributions/issues/2925)), which seems fairly far along. I think it should be in that zarr_implementations repo sometime soon: https://github.com/joshmoore/zarr_implementations/pull/2.

> I might argue bitpacking has some speed advantages given my earlier benchmarks 

Have you looked at using blosc's bit shuffling filter? E.g. `numcodecs.Blosc(shuffle=2, **)`?

> Does one of the experimental AnnData APIs support reading the data for just a single random cell?

This is an active area of development. I think the most stable thing to do would be using backed mode, and indexing to a single cell. This would only have out of core access to `X`.

You may also want to check out snapatac2, which has some more functionality around out of core access to anndata.

> One technical difference I've noticed is that blosc here defaults to 65KB+ block sizes, whereas bitpacking can decompress at 512B granularity. This may be useful for random seeks (reading individual matrix rows/columns)

You can set the chunk sizes at the zarr (`chunks=...`) and blosc (`blocksizeint=...`) levels. But choosing an appropriate chunk size can be very application and dataset specific.

**Comment by bnprks** [comment]
Thanks for all the useful links + discussion :)
That's awesome to hear about rarr -- will be great to have some more ways to get data sharing between R and python.

I have not tested the blosc bit shuffle filter yet, though from [this blog post](https://www.blosc.org/posts/new-bitshuffle-filter/) I'd expect it to provide better compression ratio at the cost of speed.
>  The drawback is that with 'bitshuffle' the compression/decompression speed is between 2x and 4x slower than with the regular 'shuffle'.

RE: AnnData backed mode -- this is only an option with the h5ad format so far, and not yet for zarr, right? Getting a backed zarr file might be a good alternative ingest format for BPCells down the road.

Lastly, to clarify my earlier comment:
> One technical difference I've noticed is that blosc here defaults to 65KB+ block sizes

I tried asking for smaller block sizes from blosc, and checking the actual resulting block size with `numcodecs.blosc.cbuffer_sizes()`. I could only get as small as 65KB with blosclz and lz4, while zstd could go smaller at the cost of running *much* slower. If we assume 2k genes detected per cell, this would equate to a minimum block size of ~8 cells of data. I would guess this is fine for most real-world access patterns, though I don't have a good way to benchmark blosc random access yet.

**Comment by bnprks** [comment]
I'm going to close this for now as I think we've had a good initial discussion. Feel free to comment more, open a new issue, or email me directly (see `DESCRIPTION` file). I'd be interested to learn if you are able to replicate some benchmarks on your hardware.
