### ISSUE TITLE
Dense h5ad matrix to BPCells

### ISSUE THREAD

**Issue by yuhanH** [bnprks/BPCells#17]
Hi,
I find that `open_matrix_anndata_hdf5` cannot open h5ad files from Genome-wide Perturb-seq datasets:
https://plus.figshare.com/articles/dataset/_Mapping_information-rich_genotype-phenotype_landscapes_with_genome-scale_Perturb-seq_Replogle_et_al_2022_processed_Perturb-seq_datasets/20029387

**Comment by bnprks** [comment]
I checked out one small file quickly -- K562_essential_raw_bulk_01.h5ad, and it looks like it's storing the matrix in dense format rather than sparse. I'm not sure if this is true for the large files as well. 

Thanks for alerting me to this problem, but I don't think BPCells is going to add support for reading AnnData dense matrices in the near future (unless many more people chime in with examples of common datasets distributed in this manner)

My recommendation for a workaround would be either:
1. Read the AnnData file in python, convert to a scipy sparse matrix in memory, then write back out to AnnData with a sparse matrix
2. Read the "X" matrix in the file directly using an R package like hdf5r (my favorite) or rhdf5

**Comment by yuhanH** [comment]
Yeah. You are right. The count matrix is saved as a dense matrix there. By converting it to a sparse matrix using scipy sparse, BPCells is able to read the h5ad file. Thank you!

**Comment by yuhanH** [comment]
One following question. If the count matrix is stored at `adata.raw.X`, can `open_matrix_anndata_hdf5` read it directly?

**Comment by bnprks** [comment]
Yeah, as listed in the [docs](https://bnprks.github.io/BPCells/reference/open_matrix_anndata_hdf5.html) just pass the correct `group` path separated by slashes. I'm assuming for your question that would be `raw/X` though you may need to dig a bit with `h5ls` to find the correct path in your particular file. (This is all assuming it's a sparse matrix format of course)

**Comment by yuhanH** [comment]
Thank you for your help! `h5ls ` is working. When i set `group = '/raw/X' `, it can read that matrix by `open_matrix_anndata_hdf5 `
