### ISSUE TITLE
write_matrix_dir error

### ISSUE THREAD

**Issue by ChengxiangQiu** [bnprks/BPCells#19]
Hi,

I got the error when I apply the write_matrix_dir function. I have tried to re-install the BPCells, but still got this problem. Any suggestion? Thanks!

```
> write_matrix_dir(dat, "tmp")
Warning: Matrix compression performs poorly with non-integers.
• Consider calling convert_matrix_type if a compressed integer matrix is intended.
This message is displayed once every 8 hours.

 *** caught segfault ***
address 0x2b, cause 'memory not mapped'

Traceback:
 1: write_function(it, dir, buffer_size, overwrite, mat@transpose)
 2: write_matrix_dir(dat, "tmp")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 3
Error in eval(formal.args[[as.character(substitute(arg))]], envir = sys.frame(sysP)) :
  Value of SET_STRING_ELT() must be a 'CHARSXP' not a 'builtin'
```

**Comment by bnprks** [comment]
Hi, @ChengxiangQiu thanks for reporting this issue. It seems pretty serious, so I'd like to get to the bottom of it as soon as possible. 

Is there any way you could share the `dat` matrix you used as e.g. an Rds file via `saveRDS`? The ideal option would be if you could subset `dat` to be as small as possible while still causing the crash, but even a link to a large data file is okay. If it's a non-public dataset you'd prefer to keep private, feel free to email me a link directly at bparks [at] stanford [dot] edu

**Comment by ChengxiangQiu** [comment]
Hi, @bnprks I really appreciate your quick feedback.
This morning I re-installed a new version of R (4.2.3), as well as all the necessary packages of BPCells, but still got the problem even though running the data/code provided in the tutorial. 

```
> # Check if we already ran import
> if (!file.exists("pbmc_3k_rna_raw")) {
+     mat_raw <- open_matrix_10x_hdf5("pbmc_3k_10x.h5", feature_type="Gene Expression") %>%
+         write_matrix_dir("pbmc_3k_rna_raw")
+ } else {
+     mat_raw <- open_matrix_dir("pbmc_3k_rna_raw")
+ }

 *** caught segfault ***
address 0x2b, cause 'memory not mapped'

Traceback:
 1: write_function(it, dir, buffer_size, overwrite, mat@transpose)
 2: write_matrix_dir(., "pbmc_3k_rna_raw")
 3: open_matrix_10x_hdf5("pbmc_3k_10x.h5", feature_type = "Gene Expression") %>%     write_matrix_dir("pbmc_3k_rna_raw")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 3
Error in eval(formal.args[[as.character(substitute(arg))]], envir = sys.frame(sysP)) :
  Value of SET_STRING_ELT() must be a 'CHARSXP' not a 'raw'
```

Some more information:
OS: CentOS Linux 7
gcc/8.1.0
R/4.2.3 (of note, I used R/4.1.0 and got the problem; Then I thought it's due to R version, so I re-installed a new one)
Then I just followed the tutorial to install BPCells. I haven't installed any other packages (e.g. seurat), so I don't think that would be due to any conflicts.

Thank you so much! I am going to analyze a big ATAC-seq dataset, so using BPCells will be super helpful.

**Comment by bnprks** [comment]
Thanks for the example. Unfortunately, I'm not getting the same bug on my setup (R/4.2.3, gcc 11.3.0, Ubuntu 22.04). This makes me a bit confused as to the cause of the issues. I'd still like to identify the cause if possible, since crashing the whole R session is a bad outcome.

My one remaining guess would be related to your gcc version being old. Could you try testing installation with a more recent gcc version? (Or with clang if you have version 9 or newer -- you can add the lines `CC=clang` and `CXX=clang++` in `~/.R/Makevars`)

If that doesn't work, my guess is the best way to work through this will be with a zoom call if possible, so I can walk you through debugging the code and see exactly where this issue is happening. Are you also in Pacific time? If so, email me (see above) and we can set up a time (hopefully April 20/21, right after my thesis defense)

If you're familiar with gdb I might be able to give you some hints on how to find where the C++ code is crashing sooner

**Comment by ChengxiangQiu** [comment]
Thanks again for those helpful suggestions. I agree with you that gcc version could be a potential reason, I will reinstall everything with a new version. If it still doesn't work, I will let you know.
