### ISSUE TITLE
support on qs file? 

### ISSUE THREAD

**Issue by realzehuali** [bnprks/BPCells#33]
BPCells is really an exciting tool for large datasets! 
For large datasets, since saveRDS and readRDS are too slow, will BPCells have support on qs file reading and writing in the future?Especially for the behaviour of queued operations of reading on-disk ount matrix.

**Comment by bnprks** [comment]
BPCells disk-backed objects are basically made up of two parts:
1. Files on disk (e.g. the folder specified by `open_matrix_dir()`
2. An S4 object that specifies any queued operations to perform

Saving (1) with an additional function is not really necessary, since by definition it's already saved on disk. Saving (2) can be done by any function that can save/load an S4 object. This includes saveRDS/readRDS, or qs (I'm not very familiar, but it appears to support S4 objects). 

I'll also advocate the `compress=FALSE` option for `saveRDS` which can greatly speed up reading/writing RDS files at the cost of a bit more disk space. The size generally shouldn't be too large even uncompressed (e.g. I have a 3 million cell matrix that uses 250MB to store the RDS file uncompressed), but I'd be happy to hear about any cases where this is not true for you. 

One last thing to mention is there's an in-development feature to recombine parts (1) and (2), via the (currently unexported) getter/setter functions [`BPCells:::all_matrix_inputs()`](https://bnprks.github.io/BPCells/reference/all_matrix_inputs.html). This allows swapping out the disk-backed data within arbitrarily complicated sets of queued operations
