### ISSUE TITLE
Data load error

### ISSUE THREAD

**Issue by abhiachoudhary** [bnprks/BPCells#53]
I just starting using BPCells and was following along the [tutorial](https://bnprks.github.io/BPCells/articles/pbmc3k.html#rna-normalization-pca-and-umap). But in the RNA matrix conversion section, the command with open_matrix_10x_hdf5 gets stuck (doesn't finish for hours):
`mat_raw <- open_matrix_10x_hdf5("pbmc_3k_10x.h5", feature_type="Gene Expression") %>% write_matrix_dir("pbmc_3k_rna_raw")
`

It shows no error, progress, nor it stops running. Is there a bug in `open_matrix_10x_hdf5`, or I'm doing something wrong?

**Comment by bnprks** [comment]
This looks likely to be a bug in BPCells, potentially related to issue #52. It looks like I'm getting a similar issue when I test this out right now too -- I see continuous 100% CPU usage on one core, whereas the import should finish within seconds if things were working properly. So probably my fault, not yours -- maybe I changed something recently that inadvertently broke the 10x matrix import. I'll do some closer looking and hopefully post back here soon with a fix.

**Comment by bnprks** [comment]
I think I likely found + fixed the cause with a one-line bugfix 🤦 . This should be fixed in 21f8dcf641fd, so if you re-install from the latest github things should be good.

It looks like I introduced this bug on October 18th in 3711a401, and the effect is to re-read the entire list of cell IDs / gene IDs for each time we want to read **one** ID (in this case resulting in about 100,000x too much work).

Thanks so much for reporting this bug and sorry for the inconvenience to you and the other ~400 people who have installed a broken version of BPCells. Let me know if you continue to have issues after this attempted fix

**Comment by abhiachoudhary** [comment]
That fixed it. Thank you!
