### ISSUE TITLE
open_matrix function for .mtx files with associated cell and gene info 

### ISSUE THREAD

**Issue by Gesmira** [bnprks/BPCells#7]
Hi, 
The `open_matrix_10x_hdf5` and `open_matrix_anndata_hdf5` functions are really handy for dealing with large datasets. Do you have or expect to make similar functionality for reading in files that are in the format of matrix.mtx, featurs.csv, and barcodes.csv? Or have tips for doing so? For example, the data format of the [1 million cell Parse dataset](https://support.parsebiosciences.com/hc/en-us/articles/7704577188500-How-to-analyze-a-1-million-cell-data-set-using-Scanpy-and-Harmony). Thanks!

**Comment by bnprks** [comment]
That is on the roadmap, but I can't guarantee it will be done particularly soon since I don't consider it a blocker for paper publication. And when it does come, it will have to be an import function since mtx files don't provide sufficient layout guarantees to allow for efficient downstream processing.

In the mean time, I'd recommend either using the Matrix::readMM functionality in R, or if it's too big to fit in an R sparse matrix you could use python to convert the dataset to anndata format. From there, it should be straightforward to pass the data to BPCells and write it in the native BPCells format

**Comment by Gesmira** [comment]
Sounds good, thank you!
